siddh_app/urls.py
from django.urls import path
from siddh_app import views

app_name = 'siddh_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('student/', views.StudentRecord.as_view(), name='studentrecord'),
    path('program/', views.ProgramRecord.as_view(), name='programrecord'),   
    path('student/new/', views.CreateStudentView.as_view(), name='create_student'),
    path('program/new/', views.CreateProgramView.as_view(), name='create_program'),
    # path('marks/update/', views.update_all_marks, name='update_marks'), 
]

siddhyarthi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('siddh_app.urls')),
    path('admin/', admin.site.urls),
]

siddh_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MaxLengthValidator, MinValueValidator, MaxValueValidator
from django.utils.text import slugify
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class College(models.Model):
    COLLEGE_CHOICES = (
        (1, "Central"),
        (2, "Affiliated"),
    )

    col_id = models.CharField(max_length=12, unique=True)
    college_name = models.CharField(max_length=100)
    college_type = models.PositiveIntegerField(choices= COLLEGE_CHOICES)

    def __str__(self):
        return self.col_id
    


class Faculty(models.Model):
    faculty_id = models.CharField(max_length=6, unique=True)
    faculty_name = models.CharField(max_length=70)

    def __str__(self):
        return self.faculty_id


class Semester(models.Model):
    semester_id = models.PositiveIntegerField(unique=True, validators=[MinValueValidator(1), MaxValueValidator(10)])
    semester_name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.semester_name
    



class Program(models.Model):
    program_id = models.CharField(max_length=12, default=None, unique=True)
    program_name = models.CharField(max_length=60)

    def get_absolute_url(self):
        return reverse("siddh_app:programrecord")

    def __str__(self):
        return self.program_id
    



class Course(models.Model):
    course_id = models.CharField(max_length=8, unique=True)
    course_name = models.CharField(max_length=50)
    program = models.ManyToManyField(Program, through='ProgramCourse')

    def __str__(self):
        return self.course_name
    


class ProgramCourse(models.Model):
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    credit_hour = models.PositiveIntegerField(default= None, null=True)

    class Meta:
        unique_together = ('program', 'course')

    def __str__(self):
        return '{} - {}'.format(self.course, self.program)
    


class Student(models.Model):

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    registration_number = models.CharField(max_length=30, default=None, unique=True, editable=False)
    batch_year = models.CharField(max_length=4, validators=[MinLengthValidator(4), MaxLengthValidator(4)])
    first_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    do_birth = models.DateField()
    email_add = models.EmailField(max_length=254)
    college = models.ForeignKey(College, default=None, on_delete=models.CASCADE)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    program = models.ForeignKey(Program, default=None, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, default=None, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.registration_number:

            # Generate registration number based on faculty code, batch year, and student count
            count = Student.objects.filter(faculty=self.faculty, batch_year=self.batch_year).count() + 1
            registration_number = f"{self.batch_year}-{self.college.college_type}-{self.faculty.pk}-{count}"
            self.registration_number = slugify(registration_number)  # Generate a slug from the registration number
        
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("siddh_app:studentrecord")


    def __str__(self):
        return self.first_name
    


class Mark(models.Model):
    student = models.ForeignKey(Student, default=None, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    marks = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(100)])

    def __str__(self):
        return f"{self.student.first_name} - {self.course.course_name}: {self.marks}"


    

siddh_app/forms.py
from django import forms
from siddh_app.models import Student, Faculty, Mark

class StudentForm(forms.ModelForm):

    class Meta():
        model = Student
        fields = ('batch_year', 'first_name', 'middle_name', 'last_name', 'do_birth', 'gender', 'faculty', 'semester')

        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),  # Use DateInput widget with type='date'
            'text': forms.TextInput(attrs={'class': 'textinputclass'}),
        }



class MarksUpdateForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ['marks']

siddh_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from siddh_app.forms import StudentForm, MarksUpdateForm
from siddh_app.models import Student, College, Faculty, Program, Mark, Semester
from django.views.generic import (TemplateView,
                                  CreateView,
                                  DetailView)

# Create your views here.
def home(request):
    return render(request, 'siddh_app/home.html', {'heading': 'Welcome to the Student App!'})


class StudentRecord(TemplateView):
    template_name = 'siddh_app/index.html'
    model = Student

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['students'] = Student.objects.all().order_by('-batch_year')
        return context
    

class ProgramRecord(TemplateView):
    template_name = 'siddh_app/program.html'
    model = Program

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['programs'] = Program.objects.all().order_by('program_name')
        return context
    


class CreateStudentView(CreateView):
    fields = ('batch_year', 'first_name', 'middle_name', 'last_name', 'gender', 'do_birth', 'email_add', 'program', 'faculty', 'college', 'semester')
    model = Student


class CreateProgramView(CreateView):
    fields = ('__all__')
    model = Program


def update_all_marks(request, student_id, program_id, semester_id):
    student = get_object_or_404(Student, pk = student_id)
    program = get_object_or_404(Program, pk = program_id)
    semester = get_object_or_404(Semester, pk = semester_id)

    marks = Mark.objects.filter(student = student, course__program = program, course__programcourse__semester = semester)

    if request.method == "POST":
        for mark in marks:
            mark_value = request.POST.get('course_{}_mark'.format(mark.course.id))
            mark.mark = mark_value
            mark.save()

        return HttpResponseRedirect('success/')
    
    return render(request, 'update_all_marks.html', {'student': student, 'program': program, 'semester': semester, 'marks': marks})

siddh_app/templates/siddh_app/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Siddhyarthi App</title>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css"
      rel="stylesheet"
    />

    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

  </head>

  <body style="margin-top: 58px">
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white" style="width: 12%">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a
            href="{% url 'siddh_app:home' %}"
            class="list-group-item list-group-item-action py-2 ripple"
            aria-current="true"
          >
            <span>Main dashboard</span>
          </a>
          <a
            href="{% url 'siddh_app:studentrecord' %}"
            class="list-group-item list-group-item-action py-2 ripple active"
          >
            <span>Student</span>
          </a>
          <a href="{% url 'siddh_app:programrecord' %}" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Program</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Assignment</span></a
          >
          <a
            href="#"
            class="list-group-item list-group-item-action py-2 ripple"
            ><span>SEO</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Orders</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>International</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Partners</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Calendar</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Users</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><span>Sales</span></a
          >
        </div>
      </div>
    </nav>

    <nav
       id="main-navbar"
       class="navbar navbar-expand-lg navbar-light bg-primary fixed-top"
       >
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
              class="navbar-toggler"
              type="button"
              data-mdb-toggle="collapse"
              data-mdb-target="#sidebarMenu"
              aria-controls="sidebarMenu"
              aria-expanded="false"
              aria-label="Toggle navigation"
              >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Brand -->
      <a class="navbar-brand" href="#">
        <img
             src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png"
             height="25"
             alt=""
             loading="lazy"
             />
      </a>
      <!-- Search form -->
      <form class="d-none d-md-flex input-group w-auto my-auto">
        <input
               autocomplete="off"
               type="search"
               class="form-control rounded"
               placeholder='Search (ctrl + "/" to focus)'
               style="min-width: 225px"
               />
        <span class="input-group-text border-0"
              ><i class="fas fa-search"></i
          ></span>
      </form>

      <!-- Right links -->
      <ul class="navbar-nav ms-auto d-flex flex-row">
        <!-- Notification dropdown -->
        <!-- Avatar -->
        <li class="nav-item dropdown">
          <a
             class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
             href="#"
             id="navbarDropdownMenuLink"
             role="button"
             data-mdb-toggle="dropdown"
             aria-expanded="false"
             >
            <img
                 src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg"
                 class="rounded-circle"
                 height="22"
                 alt=""
                 loading="lazy"
                 />
          </a>
          <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
              >
            <li><a class="dropdown-item" href="#">My profile</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- Container wrapper -->
  </nav>

    <div class="content">
        {% block body_block %} 
        
        {% endblock %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.umd.min.js"
    ></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  </body>
</html>

siddh_app/templates/siddh_app/home.html
<!DOCTYPE html>
{% extends 'siddh_app/base.html' %}

{% block body_block %}

<div class="container">
    <div class="jumbotron p-4">
        <p><h2>{{heading}}</h2></p>
    </div>
</div>

{% endblock %}

siddh_app/templates/siddh_app/index.html
<!DOCTYPE html>
{% extends 'siddh_app/base.html' %} {% block body_block %}

<div class="container">
  <div class="jumbotron p-4">
    <hr class="my-16" style="border-top: 4px solid" />

    <h1>Student Details:</h1>

    <hr class="my-4" style="border-top: 4px solid" />

    <table class="table table-striped">
      <thead>
        <td>Batch</td>
        <td>Registration Number</td>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Gender</td>
        <td>Faculty</td>
        <td>Semester</td>
        <td>Update</td>
      </thead>

      {% for student in students %}
      <tr>
        <td>{{student.batch_year}}</td>
        <td>{{student.registration_number}}</td>
        <td>{{student.first_name}}</td>
        <td>{{student.last_name}}</td>
        <td>{{student.gender}}</td>
        <td>{{student.faculty}}</td>
        <td>{{student.semester}}</td>
        <td>
          <a href="#">
            <input
              type="submit"
              class="btn btn-primary btn-sm"
              value="Update"
            />
          </a>
        </td>
      </tr>
      {% endfor %}
    </table>

    <hr class="my-4" style="border-top: 4px solid" />

    <div class="container">
      <a
        class="btn btn-primary btn-sm"
        href="{% url 'siddh_app:create_student' %}"
        >Create Student</a
      >
    </div>
  </div>
</div>

{% endblock %}

siddh_app/templates/siddh_app/program.html
<!DOCTYPE html>
{% extends 'siddh_app/base.html' %} 


{% block body_block %}

<div class="container">
  <div class="jumbotron p-4">
    <hr class="my-16" style="border-top: 4px solid" />

    <h1>Program Details:</h1>

    <hr class="my-4" style="border-top: 4px solid" />

    <table class="table table-striped">
      <thead>
        <td>Program ID</td>
        <td>Program Name</td>
        <td></td>
      </thead>

      {% for program in programs %}
      <tr>
        <td>{{program.program_id}}</td>
        <td>{{program.program_name}}</td>
          <td>
            <a href="#">
                <input
                  type="submit"
                  class="btn btn-primary btn-sm"
                  value="Update"
                />
              </a>
          </td>
      </tr>
      {% endfor %}
    </table>

    <hr class="my-4" style="border-top: 4px solid" />

    <div class="container">
      <a
        class="btn btn-primary btn-sm"
        href="{% url 'siddh_app:create_program' %}"
        >Create Program</a
      >
    </div>
  </div>
</div>

{% endblock %}

siddh_app/templates/siddh_app/program_form.html
<!DOCTYPE html>

{% extends 'siddh_app/base.html' %}

{% block body_block %}

<div class="container">

    <div class="jumbotron p-4">
        
        <hr class="my-16" style="border-top: 4px solid;">

        <h1>Add a New Program:</h1>

        <hr class="my-4" style="border-top: 4px solid;">
    </div>

    <div class="jumbotron">
        <form action="{% url 'siddh_app:create_program' %}" method="post">
        
            {% csrf_token %}
    
            {{form.as_p}}
    
            <input type="submit" class="btn btn-primary" value="Submit">
    
        </form>
    </div>

</div>

{% endblock %}

siddh_app/templates/siddh_app/student_form.html
<!DOCTYPE html>

{% extends 'siddh_app/base.html' %}

{% block body_block %}

<div class="container">

    <div class="jumbotron p-4">
        
        <hr class="my-16" style="border-top: 4px solid;">

        <h1>Student Details:</h1>

        <hr class="my-4" style="border-top: 4px solid;">
    </div>

    <div class="jumbotron">
        <form action="{% url 'siddh_app:create_student' %}" method="post">
        
            {% csrf_token %}
    
            {{form.as_p}}
    
            <input type="submit" class="btn btn-primary" value="Submit">
    
        </form>
    </div>

</div>

{% endblock %}

siddh_app/templates/siddh_app/update_all_marks.html
<!DOCTYPE html>

{% extends 'siddh_app/base.html' %}

{% block body_block %}

    <form action="{% url 'siddh_app:update_marks' %}" method="post">
        
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Marks">

    </form>

{% endblock %}